### ISSUE TITLE
Noob Init Question

### ISSUE THREAD

**Issue by aadityaverma** [Wordcab/wordcab-transcribe#20]
Getting this output while trying any yt link.

{'detail': [{'loc': ['query', 'url'], 'msg': 'field required', 'type': 'value_error.missing'}]}

.....
Running docker here, passes nox

**Comment by chainyo** [comment]
Hi @aadityaverma 
Let me know if you use the docs UI or a script request.

Could you share a code snippet or a screenshot of the docs endpoint you are using?

**Comment by aadityaverma** [comment]
Hey thanks for replying so quickly, getting the above error when I run
//
 import requests

url = "https://youtube.com/watch?v=XfKQUn9wm7I"
data = {"url": url}
response = requests.post("http://localhost:5001/api/v1/youtube", json=data)
print(response.json())

**Comment by aadityaverma** [comment]
![image](https://user-images.githubusercontent.com/18281542/230963543-353cbfbf-893d-4818-ba80-7aa37bbccfe6.png)

**Comment by aadityaverma** [comment]
And when I run
//
 curl -X 'POST' \
  'http://localhost:5001/api/v1/youtube?url=https%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3DXfKQUn9wm7I&num_speakers=2&source_lang=Hindi&timestamps=seconds' \
  -H 'accept: application/json' \
  -d ''
![image](https://user-images.githubusercontent.com/18281542/230964628-6ec9a5e9-6c5c-44d9-b7d5-87e68b7ba513.png)

This is the error 

(tts) aditya@panel:~/wordcab-transcribe$ sudo curl -X 'POST' \
>   'http://localhost:5001/api/v1/youtube?url=https%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3DXfKQUn9wm7I&num_speakers=2&source_lang=Hindi&timestamps=seconds' \
>   -H 'accept: application/json' \
>   -d ''
[sudo] password for aditya: 
Sorry, try again.
[sudo] password for aditya: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/wordcab_transcribe/main.py", line 206, in inference_with_youtube
    utterances = [
TypeError: 'ValueError' object is not iterable

**Comment by aadityaverma** [comment]
Conda is python 3.9

**Comment by aadityaverma** [comment]
Maybe my  selecting "Hindi" or "hi" is causing the above cause the defaults (spk=0) is using the gpu.

**Comment by aadityaverma** [comment]
File "/app/wordcab_transcribe/main.py", line 206, in inference_with_youtube
    utterances = [
TypeError: 'OutOfMemoryError' object is not iterable

I am running a Rtx super 2060, 8gb VRam ~ 5 available on startup and container run

**Comment by chainyo** [comment]
It could come from the lack of VRAM. It uses 5.3GB on my side. Could you free some VRAM and give it a new try?

Also, if you are using Docker, you can do `docker logs container-name` to access the logs. In this case, `docker logs wordcab-transcribe` (if you used the commands provided in the README file.

**Comment by chainyo** [comment]
I tried to reproduce your bug with this Python code snippet:

```python
import requests

url = "https://youtube.com/watch?v=XfKQUn9wm7I"
response = requests.post(
    f"http://localhost:5001/api/v1/youtube?url={url}&source_lang=hi")
print(response.json())
```

I can confirm that you need at least 6GB of VRAM for ASR:

![CleanShot 2023-04-11 at 10 34 25](https://user-images.githubusercontent.com/50595514/231105322-ed0b0d95-0205-43d3-a47f-323dddbd39aa.png)

But the problem comes after during diarization because the application is trying to diarize everything at once, which causes CUDA OOM on long videos.

Here is the error I get:

```bash
2023-04-11 08:33:23.590 | DEBUG    | wordcab_transcribe.service:runner:121 - Longest wait: 0.1002820310000061
2023-04-11 08:36:45.457 | ERROR    | wordcab_transcribe.service:runner:149 - Error processing batch: CUDA out of memory. Tried to allocate 3.65 GiB (GPU 0; 23.70 GiB total capacity; 15.10 GiB already allocated; 1.03 GiB free; 19.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
INFO:     172.17.0.1:60570 - "POST /api/v1/youtube?url=https://youtube.com/watch?v=XfKQUn9wm7I&source_lang=hi HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/wordcab_transcribe/main.py", line 206, in inference_with_youtube
    utterances = [
TypeError: 'OutOfMemoryError' object is not iterable
```

Thanks for reporting your issue @aadityaverma and for providing explanations and code snippets. I will investigate how to fix this for long videos.

**Comment by chainyo** [comment]
For the record, on the video you are trying to transcribe, diarization takes more than 24GB of VRAM 😯.

![CleanShot 2023-04-11 at 10 46 27](https://user-images.githubusercontent.com/50595514/231106744-41919ffb-23a0-4e76-99b6-1b33eb5c900a.png)

**Comment by aleksandr-smechov** [comment]
@chainyo would it be possible to confirm those extra ~17GB of VRAM are caused by diarization? Seems unlikely with the small speechbrain model and agglomerative clustering.

**Comment by chainyo** [comment]
It seems to be at the end of the `faster-whisper` process, but I still need to inspect it closely.

**Comment by aleksandr-smechov** [comment]
And this happens even with a batch size of 1? 

As an aside, I was trying a notebook that used a different method of diarization. It split the file into multiple smaller files, then transcribed those, and then the diarization. 

I think the speechbrain model and agglomerative clustering is less prone to mistakes, but splitting the file sped up the process by 2x vs what it is right now. It also probably uses less memory.

Should we explore this approach? @chainyo

**Comment by chainyo** [comment]
Closed by #31 

P.S.: On long videos, like the one linked above, transcription takes less than 5.3GB and is 30min long. New NVIDIA NeMo diarization takes 5min and 13.5GB of VRAM.
