### ISSUE TITLE
error after processing audio without speech

### ISSUE THREAD

**Issue by michalblaha** [Wordcab/wordcab-transcribe#280]
This is log for the audio file without any speech. It looks that it fails during creating of the result structure…

version 0.5.2 in docker on NVIDIA RTX 4090

```
2023-11-12 17:36:24,638 - faster_whisper - INFO - Processing audio with duration 00:33.344
2023-11-12 17:36:24,942 - faster_whisper - INFO - VAD filter removed 00:33.344 of audio
2023-11-12 17:36:25.196 | DEBUG    | wordcab_transcribe.logging:time_and_tell_async:137 - transcription executed in 3.9033 secs
2023-11-12 17:36:25.197 | DEBUG    | wordcab_transcribe.logging:time_and_tell:102 - format_segments executed in 0.0000 secs
2023-11-12 17:36:25.199 | ERROR    | wordcab_transcribe.router.v1.audio_url_endpoint:inference_with_audio_url:99 - Error in post-processing: list index out of range
Traceback (most recent call last):
  File "/app/src/wordcab_transcribe/services/asr_service.py", line 719, in process_post_processing
    self.local_services.post_processing.single_channel_speaker_mapping(
  File "/app/src/wordcab_transcribe/services/post_processing_service.py", line 72, in single_channel_speaker_mapping
    utterances = self.reconstruct_utterances(
  File "/app/src/wordcab_transcribe/services/post_processing_service.py", line 285, in reconstruct_utterances
    transcript_segments[0].start,
IndexError: list index out of range

2023-11-12 17:36:25.200 | INFO     | wordcab_transcribe.logging:dispatch:75 - Task [6fda223e-3cfb-456d-86dc-f1bac52a0c4f] | Status: 500, Time: 4.3434 secs
INFO:     10.10.xxx.xxx:45694 - "POST /api/v1/audio-url?url=https%3A%2F%2Fsomedata.hlidacstatu.cz%2Fmp3%2Fvyjadreni-politiku%2F2efbf97493b0749085e22e5d97c0c889.mp3 HTTP/1.1" 500 Internal Server Error
```

**Comment by aleksandr-smechov** [comment]
@michalblaha Are you able to upload the file here? Or you can send it to info@wordcab.com.
