### ISSUE TITLE
Can't test the API

### ISSUE THREAD

**Issue by utility-aagrawal** [Wordcab/wordcab-transcribe#303]
Hi,

I just built and ran the docker. I am trying to test the API using code given in the readme file for audio and youtube video. For both scripts, I am getting this error. Can someone help me why?

Traceback (most recent call last):
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aagrawal/sentiment_summary/wordcab-transcribe/localfile_test.py", line 16, in <module>
    response = requests.post(
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/aagrawal/sentiment_summary/wordcab_venv/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by yf-chau** [comment]
It might be useful to check and share your docker logs.

**Comment by aleksandr-smechov** [comment]
@utility-aagrawal I've removed the hatch dependency and resolved a few other issues.
