### ISSUE TITLE
None of the API endpoints seem available

### ISSUE THREAD

**Issue by callmephilip** [Wordcab/wordcab-transcribe#78]
I have wordcab running in docker. When i try accessing any endpoint (a simple http://localhost:5001 included) i get an error and container log shows the following:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wordcab_transcribe/main.py", line 25, in <module>
    from wordcab_transcribe.dependencies import asr
  File "/app/wordcab_transcribe/dependencies.py", line 27, in <module>
    asr = ASRAsyncService()
  File "/app/wordcab_transcribe/services/asr_service.py", line 100, in __init__
    "transcription": TranscribeService(
  File "/app/wordcab_transcribe/services/transcribe_service.py", line 197, in __init__
    self.model = WhisperModel(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 117, in __init__
    model_path = download_model(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/faster_whisper/utils.py", line 88, in download_model
    return huggingface_hub.snapshot_download(repo_id, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 215, in _inner_hf_hub_download
    return hf_hub_download(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 541, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

Looks like an issue with HF but i am not 100% sure. This is running with standard `.env` included in the repo

**Comment by chainyo** [comment]
Could you assert you are using this docker run command:

```
docker run -d --name wordcab-transcribe \
    --gpus all \
    --shm-size 1g \
    --restart unless-stopped \
    -p 5001:5001 \
    -v ~/.cache:/root/.cache \
    wordcab-transcribe:latest
```

And not this one:

```
docker run -d --name wordcab-transcribe \
    --gpus all \
    --shm-size 1g \
    --restart unless-stopped \
    -p 5001:5001 \
    -v ~/.cache:/root/.cache \
    -v /path/to/whisper/models:/app/whisper/models \
    wordcab-transcribe:latest
```

**Comment by callmephilip** [comment]
@chainyo another interesting update - seems like everything is working now

**Comment by callmephilip** [comment]
i suspect this might have been an issue with HF connectivity. any plans on supporting local models? as far as i can tell, `faster_whisper` already supports this option

**Comment by chainyo** [comment]
> any plans on supporting local models? as far as i can tell, faster_whisper already supports this option

We do! By updating the `.env` file with the same mounted path you use in the docker run command, you should be able to run local models:

```
docker run -d --name wordcab-transcribe \
    --gpus all \
    --shm-size 1g \
    --restart unless-stopped \
    -p 5001:5001 \
    -v ~/.cache:/root/.cache \
    -v /path/to/whisper/models:/app/whisper/models \
    wordcab-transcribe:latest
```

**Comment by callmephilip** [comment]
sweet! thank you. closing this as resolved

**Comment by chainyo** [comment]
Great feel free to open another Issues if needed
